// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7CjbdQXOzJ06B0JnV_9y_wwPFP20JaWo',
    appId: '1:190795040487:web:df4cb4c5c9a103e4368442',
    messagingSenderId: '190795040487',
    projectId: 'learntajwiid',
    authDomain: 'learntajwiid.firebaseapp.com',
    storageBucket: 'learntajwiid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrbIugGMbHCAye1w9_8uNAvQAaijqTIpY',
    appId: '1:190795040487:android:0a8ed375ac168b80368442',
    messagingSenderId: '190795040487',
    projectId: 'learntajwiid',
    storageBucket: 'learntajwiid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOYRir-EPcfqVOvZmCRwYpRc_MRZpKOyM',
    appId: '1:190795040487:ios:7c293809cc139501368442',
    messagingSenderId: '190795040487',
    projectId: 'learntajwiid',
    storageBucket: 'learntajwiid.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );
}
